# Site settings
title: SmartWork
description: A blog about Enock Khondowe's Activities.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Enock Khondowe
user_description: Technology enthusiast, nerd, web designer, programmer. I like to make and improve things.  Reading and Writing Articles are my favorite things.
user_title: Software Developer
email: enockkhondowe94@yahoo.com
facabook_username: Enock Khondowe
github_username:  enockkays
Linkedin_username: Enock Khondowe
Intagram_username: enockkhondowe

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
